org: arash
app: timestamp-genius
service: timestamp-genius-backend
frameworkVersion: '3'

provider:
  name: aws
  profile: appricot2
  runtime: nodejs18.x

plugins:
  - serverless-associate-waf

# Associate WAF Web ACL with API Gateway of current stack
custom:
  associateWaf:
    name: TSG-WAF-WebACL2
    version: V2 #(optional) Regional | V2

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: get

resources:
  Resources:
    WAFRegionalWebACL:
      Type: "AWS::WAFv2::WebACL"
      Properties:
        Name: TSG-WAF-WebAC2
        Scope: REGIONAL
        Description: WAF Regional Web ACL to Prevent HTTP Flood DDos Attack
        DefaultAction:
          Allow: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: ApiGateway-HTTP-Flood-Prevent-Metric
        Rules:
          - Name: HTTP-Flood-Prevent-Rule
            Priority: 0
            Action:
              Block: {}
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: HTTP-Flood-Prevent-Rule-Metric
            Statement:
              RateBasedStatement:
                AggregateKeyType: IP
                Limit: 100  # rate limit adjust as per your real traffic