org: arash
app: timestamp-genius
service: timestamp-genius-backend
frameworkVersion: '3'

provider:
  name: aws
  profile: appricot2
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  environment:
    DB: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

plugins:
  - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
          cors: true

resources:
  Resources:
    TimestampGeniusTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: "PK"
            AttributeType: "S"
          - AttributeName: "SK"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "PK"
            KeyType: "HASH" 
          - AttributeName: "SK"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits:  1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
            AttributeName: ttl
            Enabled: true
        TableName: ${self:provider.environment.DB}